In [ ]:
excel_file_path = r'C:\Users\mouli\Downloads\Adyar_RF_1991_2022.xlsx'

In [ ]:
import pandas as pd
import numpy as np
import scipy as stats
import matplotlib.pyplot as plot

In [ ]:
df = pd.read_excel(excel_file_path, sheet_name='Sheet2')

In [ ]:
pip install --upgrade pandas

Requirement already satisfied: pandas in e:\anaconda\lib\site-packages (2.0.3)
Note: you may need to restart the kernel to use updated packages.

ERROR: Could not install packages due to an OSError: Could not find a suitable TLS CA certificate bundle, invalid path: C:\Program Files\PostgreSQL\16\ssl\certs\ca-bundle.crt

WARNING: There was an error checking the latest version of pip.

In [ ]:
df.shape

(90278, 10)

In [ ]:
Chem = df[df['Station Name'].str.strip() == "Chembarambakkam"]
print(Chem)

       Station Code                    Station Name      District  \
0      CHEMBARMPAKM  Chembarambakkam                 Kancheepuram
1      CHEMBARMPAKM  Chembarambakkam                 Kancheepuram
2      CHEMBARMPAKM  Chembarambakkam                 Kancheepuram
3      CHEMBARMPAKM  Chembarambakkam                 Kancheepuram
4      CHEMBARMPAKM  Chembarambakkam                 Kancheepuram
...             ...                             ...           ...
11683  CHEMBARMPAKM  Chembarambakkam                 Kancheepuram
11684  CHEMBARMPAKM  Chembarambakkam                 Kancheepuram
11685  CHEMBARMPAKM  Chembarambakkam                 Kancheepuram
11686  CHEMBARMPAKM  Chembarambakkam                 Kancheepuram
11687  CHEMBARMPAKM  Chembarambakkam                 Kancheepuram

      Tahsil / Taluk   Latitude  Longitude  Year  Month  Day    RF
0         Kundrathur  13°00'30"  80°05'05"  1991      1    1  82.0
1         Kundrathur  13°00'30"  80°05'05"  1991      1    2   0.0
2         Kundrathur  13°00'30"  80°05'05"  1991      1    3   0.0
3         Kundrathur  13°00'30"  80°05'05"  1991      1    4   0.0
4         Kundrathur  13°00'30"  80°05'05"  1991      1    5   0.0
...              ...        ...        ...   ...    ...  ...   ...
11683     Kundrathur  13°00'30"  80°05'05"  2022     12   27   0.0
11684     Kundrathur  13°00'30"  80°05'05"  2022     12   28   0.0
11685     Kundrathur  13°00'30"  80°05'05"  2022     12   29   0.0
11686     Kundrathur  13°00'30"  80°05'05"  2022     12   30   0.0
11687     Kundrathur  13°00'30"  80°05'05"  2022     12   31   0.0

[11688 rows x 10 columns]

In [ ]:
Nung = df[df['Station Name'].str.strip() == "Chennai - Nungambakkam"]
print(Nung)

       Station Code                    Station Name District Tahsil / Taluk  \
40695  CHN_NUNGMBKM  Chennai - Nungambakkam          Chennai      Teynampet
40696  CHN_NUNGMBKM  Chennai - Nungambakkam          Chennai      Teynampet
40697  CHN_NUNGMBKM  Chennai - Nungambakkam          Chennai      Teynampet
40698  CHN_NUNGMBKM  Chennai - Nungambakkam          Chennai      Teynampet
40699  CHN_NUNGMBKM  Chennai - Nungambakkam          Chennai      Teynampet
...             ...                             ...      ...            ...
51282  CHN_NUNGMBKM  Chennai - Nungambakkam          Chennai      Teynampet
51283  CHN_NUNGMBKM  Chennai - Nungambakkam          Chennai      Teynampet
51284  CHN_NUNGMBKM  Chennai - Nungambakkam          Chennai      Teynampet
51285  CHN_NUNGMBKM  Chennai - Nungambakkam          Chennai      Teynampet
51286  CHN_NUNGMBKM  Chennai - Nungambakkam          Chennai      Teynampet

        Latitude  Longitude  Year  Month  Day   RF
40695  13°04'05"  80°14'46"  1994      1    1  0.0
40696  13°04'05"  80°14'46"  1994      1    2  0.0
40697  13°04'05"  80°14'46"  1994      1    3  0.0
40698  13°04'05"  80°14'46"  1994      1    4  0.0
40699  13°04'05"  80°14'46"  1994      1    5  0.0
...          ...        ...   ...    ...  ...  ...
51282  13°04'05"  80°14'46"  2022     12   27  0.0
51283  13°04'05"  80°14'46"  2022     12   28  0.0
51284  13°04'05"  80°14'46"  2022     12   29  0.0
51285  13°04'05"  80°14'46"  2022     12   30  0.0
51286  13°04'05"  80°14'46"  2022     12   31  0.0

[10592 rows x 10 columns]

In [ ]:
Thar = df[df['Station Name'].str.strip() == "Chennai - Tharamani"]
print(Thar)

       Station Code                    Station Name District Tahsil / Taluk  \
51287  CHN_TARAMANI  Chennai - Tharamani             Chennai          Adyar
51288  CHN_TARAMANI  Chennai - Tharamani             Chennai          Adyar
51289  CHN_TARAMANI  Chennai - Tharamani             Chennai          Adyar
51290  CHN_TARAMANI  Chennai - Tharamani             Chennai          Adyar
51291  CHN_TARAMANI  Chennai - Tharamani             Chennai          Adyar
...             ...                             ...      ...            ...
59227  CHN_TARAMANI  Chennai - Tharamani             Chennai          Adyar
59228  CHN_TARAMANI  Chennai - Tharamani             Chennai          Adyar
59229  CHN_TARAMANI  Chennai - Tharamani             Chennai          Adyar
59230  CHN_TARAMANI  Chennai - Tharamani             Chennai          Adyar
59231  CHN_TARAMANI  Chennai - Tharamani             Chennai          Adyar

        Latitude  Longitude  Year  Month  Day   RF
51287  12°59'09"  80°14'41"  2001      4    1  0.0
51288  12°59'09"  80°14'41"  2001      4    2  0.0
51289  12°59'09"  80°14'41"  2001      4    3  0.0
51290  12°59'09"  80°14'41"  2001      4    4  0.0
51291  12°59'09"  80°14'41"  2001      4    5  0.0
...          ...        ...   ...    ...  ...  ...
59227  12°59'09"  80°14'41"  2022     12   27  0.0
59228  12°59'09"  80°14'41"  2022     12   28  0.0
59229  12°59'09"  80°14'41"  2022     12   29  0.0
59230  12°59'09"  80°14'41"  2022     12   30  0.0
59231  12°59'09"  80°14'41"  2022     12   31  0.0

[7945 rows x 10 columns]

In [ ]:
reference_dates = pd.date_range(start='1991-01-01', end='2022-12-31')
unique_years = Thar['Year'].unique()

missing_years = set(range(1991, 2023)) - set(unique_years)

if not missing_years:
    print("The DataFrame contains data for all years from 1991 to 2022 Thar.")
else:
    print(f"The DataFrame is missing data for the following years-Thar: {missing_years}")

The DataFrame is missing data for the following years-Thar: {1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000}

In [ ]:
reference_dates = pd.date_range(start='1991-01-01', end='2022-12-31')
unique_years = Chem['Year'].unique()

missing_years = set(range(1991, 2023)) - set(unique_years)

if not missing_years:
    print("The DataFrame contains data for all years from 1991 to 2022 Chem.")
else:
    print(f"The DataFrame is missing data for the following years-Chem: {missing_years}")

The DataFrame contains data for all years from 1991 to 2022 Chem.

In [ ]:
reference_dates = pd.date_range(start='1991-01-01', end='2022-12-31')
unique_years = Nung['Year'].unique()

missing_years = set(range(1991, 2023)) - set(unique_years)

if not missing_years:
    print("The DataFrame contains data for all years from 1991 to 2022 Nung.")
else:
    print(f"The DataFrame is missing data for the following years-Nung: {missing_years}")

The DataFrame is missing data for the following years-Nung: {1992, 1993, 1991}

In [ ]:
df1 = Thar[(Thar["Month"] == 12) & (Thar["Year"] == 2015)]

print("Standard deviation of Tharamani's Rainfall at 2015/12 is: ",df1['RF'].std())

Standard deviation of Tharamani's Rainfall at 2015/12 is:  54.0736256343822

In [ ]:
for i in range(1,13):
    df1 = Thar[(Thar["Month"] == i) & (Thar["Year"] == 2015)]
    sd = df1["RF"].std()
    mean = df1["RF"].mean()
    max = df1["RF"].max()
    min = df1["RF"].min()
    print(f"The Standar Deviation for Thanbaram For the month {i} is : {sd} , Mean : {mean} ,max : {max} , Min : {min}")

The Standar Deviation for Thanbaram For the month 1 is : 1.1898133946037484 , Mean : 0.2967741935483871 ,max : 5.8 , Min : 0.0
The Standar Deviation for Thanbaram For the month 2 is : 0.0 , Mean : 0.0 ,max : 0.0 , Min : 0.0
The Standar Deviation for Thanbaram For the month 3 is : 0.0 , Mean : 0.0 ,max : 0.0 , Min : 0.0
The Standar Deviation for Thanbaram For the month 4 is : 21.952212728519203 , Mean : 4.196666666666666 ,max : 120.3 , Min : 0.0
The Standar Deviation for Thanbaram For the month 5 is : 1.4230891734880575 , Mean : 0.35806451612903223 ,max : 6.8 , Min : 0.0
The Standar Deviation for Thanbaram For the month 6 is : 5.79937471857413 , Mean : 1.7966666666666669 ,max : 27.7 , Min : 0.0
The Standar Deviation for Thanbaram For the month 7 is : 7.375052396387592 , Mean : 3.5161290322580645 ,max : 21.0 , Min : 0.0
The Standar Deviation for Thanbaram For the month 8 is : 15.495973115480641 , Mean : 6.841935483870968 ,max : 63.2 , Min : 0.0
The Standar Deviation for Thanbaram For the month 9 is : 6.621092211181289 , Mean : 1.8900000000000001 ,max : 30.7 , Min : 0.0
The Standar Deviation for Thanbaram For the month 10 is : 8.130251487334931 , Mean : 3.696774193548387 ,max : 30.0 , Min : 0.0
The Standar Deviation for Thanbaram For the month 11 is : 43.80685215313356 , Mean : 29.73793103448276 ,max : 200.0 , Min : 0.0
The Standar Deviation for Thanbaram For the month 12 is : 54.0736256343822 , Mean : 14.096774193548388 ,max : 300.0 , Min : 0.0

In [ ]:
columns = ['Year', 'Month', 'Std','Mean','Max','Min']
data = pd.DataFrame()
print(data)

Empty DataFrame
Columns: []
Index: []

In [ ]:
for j in range(1991,2022):
       for i in range(1,13):
            df1 = Thar[(Thar["Month"] == i) & (Thar["Year"] == j)]
            sd = df1["RF"].std()
            mean = df1["RF"].mean()
            max = df1["RF"].max()
            min = df1["RF"].min()
            data = data.append({'Year': j, 'Month': i, 'Std': sd, 'Mean': mean, 'Max': max_val, 'Min': min_val}, ignore_index=True)

AttributeError: 'DataFrame' object has no attribute 'append'

In [ ]:
i = 1

for j in range(1991,2022):
        df1 = Thar[(Thar["Year"] == j)]
        sd = df1["RF"].std()
        mean = df1["RF"].mean()

        m = mean/(sd*sd)

        n = (mean*mean)/(sd*sd)



        print(f"The Gamma distribution for Thanbaram For the Year {j} is : {m}, {n}")

        i= i + 1

The Lambda for Thanbaram For the Year 1991 is : nan, nan
The Lambda for Thanbaram For the Year 1992 is : nan, nan
The Lambda for Thanbaram For the Year 1993 is : nan, nan
The Lambda for Thanbaram For the Year 1994 is : nan, nan
The Lambda for Thanbaram For the Year 1995 is : nan, nan
The Lambda for Thanbaram For the Year 1996 is : nan, nan
The Lambda for Thanbaram For the Year 1997 is : nan, nan
The Lambda for Thanbaram For the Year 1998 is : nan, nan
The Lambda for Thanbaram For the Year 1999 is : nan, nan
The Lambda for Thanbaram For the Year 2000 is : nan, nan
The Lambda for Thanbaram For the Year 2001 is : 0.01995795551942446, 0.10780198955837487
The Lambda for Thanbaram For the Year 2002 is : 0.015380785775028414, 0.05630884602668348
The Lambda for Thanbaram For the Year 2003 is : 0.04604036823984505, 0.07833169500532541
The Lambda for Thanbaram For the Year 2004 is : 0.027452041194754407, 0.08748275477459508
The Lambda for Thanbaram For the Year 2005 is : 0.009799875682098549, 0.05810655055122652
The Lambda for Thanbaram For the Year 2006 is : 0.014663338872454858, 0.05512129863045989
The Lambda for Thanbaram For the Year 2007 is : 0.021757707470542124, 0.07760825229348742
The Lambda for Thanbaram For the Year 2008 is : 0.017041652292102222, 0.062234624190229036
The Lambda for Thanbaram For the Year 2009 is : 0.021472844658382003, 0.06699880511683541
The Lambda for Thanbaram For the Year 2010 is : 0.02374302455105034, 0.09072437353794496
The Lambda for Thanbaram For the Year 2011 is : 0.024410960028975734, 0.09990436189392865
The Lambda for Thanbaram For the Year 2012 is : 0.023030671965596633, 0.06318332710561635
The Lambda for Thanbaram For the Year 2013 is : 0.0295825761251748, 0.07604748268014114
The Lambda for Thanbaram For the Year 2014 is : 0.02071411820884136, 0.07025207378280744
The Lambda for Thanbaram For the Year 2015 is : 0.010319179706306426, 0.05646915949723014
The Lambda for Thanbaram For the Year 2016 is : 0.014133639299286311, 0.045752830168837216
The Lambda for Thanbaram For the Year 2017 is : 0.013950004749630204, 0.05130926404487273
The Lambda for Thanbaram For the Year 2018 is : 0.024245577419781464, 0.05544598211586737
The Lambda for Thanbaram For the Year 2019 is : 0.026445519260700583, 0.09679060049416414
The Lambda for Thanbaram For the Year 2020 is : 0.016403934534178075, 0.07270170002155808
The Lambda for Thanbaram For the Year 2021 is : 0.01642631337388574, 0.09709976365889281

In [1]:
columns = ['Year', 'Month', 'Std', 'Mean', 'Max', 'Min']
df = pd.DataFrame(columns=columns)

for j in range(2001, 2022):
    for i in range(1, 13):
        df1 = Thar[(Thar["Month"] == i) & (Thar["Year"] == j)]
        sd = df1["RF"].std()
        mean = df1["RF"].mean()
        max_val = df1["RF"].max()
        min_val = df1["RF"].min()
        df.append({'Year': j, 'Month': i, 'Std': sd, 'Mean': mean, 'Max': max_val, 'Min': min_val}, ignore_index=True)
print(result_data)

NameError: name 'pd' is not defined